const SECS_PER_MIN = 60;
const SECS_PER_HOUR = 60 * SECS_PER_MIN;
const SECS_PER_DAY = 24 * SECS_PER_HOUR;
const SECS_PER_BLOCK = 5;

export { SECS_PER_DAY, SECS_PER_BLOCK, SECS_PER_MIN, SECS_PER_HOUR };
